python main.py \
--algorithm reg_maml \
--model-type regconv \
--original-conv \
--condition-type affine \
--embedding-type RegConvGRU \
--embedding-hidden-size 256 \
--no-rnn-aggregation True \
--fast-lr .5 \
--inner-loop-grad-clip 10.0 \
--num-updates 5 \
--num-batches-meta-train 60000 \
--num-batches-meta-val 100 \
--meta-batch-size 10 \
--slow-lr 0.001 \
--model-grad-clip 2.5 \
--dataset miniimagenet \
--num-classes-per-batch 5 \
--num-train-samples-per-class 1 \
--num-val-samples-per-class-meta-train 15 \
--num-val-samples-per-class-meta-val 15 \
--img-side-len 84 \
--output-folder  \
--device cuda \
--device-number 2 \
--log-interval 50 \
--save-interval 1000 \
--val-interval 1000
--num-channels 64 \
--modulation-mat-rank 32 \
--l2-inner-loop 10 \
--modulation-mat-spec-norm 1.