python main_minmax.py \
--algorithm ProtonetCosine \
--model-type resnet12 \
--classifier-type avg-classifier-2 \
--img-side-len 84 \
--gamma 0. \
--lr 0.1 \
--momentum 0.9 \
--weight-decay 0.0005 \
--eps 0. \
--grad-clip 0. \
--dataset-path data/filelists/CUB \
--n-epochs 200 \
--num-classes-train 100 \
--n-way-train 100 \
--n-shot-train 3 \
--batch-size-train 64 \
--n-iterations-val 400 \
--batch-size-val 1 \
--n-way-val 5 \
--n-shot-val 5 \
--n-query-val 15 \
--output-folder minmax_CUB_r12_n100_s3_q64_noEPSreset \
--device cuda \
--device-number 0,1,2,3 \
--log-interval 45 \
--train-aug \
--checkpoint train_dir/classical_CUB_r12_classifier_bs128_parametric_metal_gradanalysis_optsaved_saugfalse/classical_resnet_095.pt