python main_meta_classical.py \
--algorithm Protonet \
--model-type resnet12 \
--img-side-len 84 \
--lr 0.001 \
--weight-decay 0.0005 \
--grad-clip 0. \
--dataset-path data/filelists/FC100 \
--n-epochs 60 \
--n-tf-updates 1 \
--num-classes-train 300 \
--batch-size-train 1 \
--n-way-train 5 \
--n-shot-train 5 \
--n-query-train 5 \
--batch-size-val 1 \
--n-way-val 5 \
--n-shot-val 5 \
--n-query-val 15 \
--n-iterations-val 400 \
--output-folder metal_FC100_r12_n60_s5_q5_euc_fixS \
--device cuda \
--device-number 0,1,2,3 \
--log-interval 100 \
--train-aug
# --checkpoint train_dir/classical_miniimagenet_avg_classifier_5/classical_resnet_163.pt
# --restart-iter 150