python main.py \
--algorithm metaoptnet \
--model-type impregconv \
--original-conv \
--num-channels 64 \
--retain-activation True \
--use-group-norm True \
--add-bias True \
--optimizer sgd \
--slow-lr 0.1 \
--optimizer-update-interval 2 \
--model-grad-clip 0. \
--dataset miniimagenet \
--num-batches-meta-train 80000 \
--num-batches-meta-val 100 \
--meta-batch-size 4 \
--num-classes-per-batch-meta-train 5 \
--num-classes-per-batch-meta-val 5 \
--num-classes-per-batch-meta-test 5 \
--num-train-samples-per-class-meta-train 15 \
--num-train-samples-per-class-meta-val 5 \
--num-train-samples-per-class-meta-test 5 \
--num-val-samples-per-class-meta-train 15 \
--num-val-samples-per-class-meta-val 15 \
--num-val-samples-per-class-meta-test 15 \
--img-side-len 84 \
--output-folder minim_5w15s_SVM \
--device cuda \
--device-number 2 \
--log-interval 50 \
--save-interval 1000 \
--val-interval 1000 \
--verbose True


