python main.py \
--algorithm mmaml \
--model-type gatedconv \
--condition-type affine \
--embedding-type ConvGRU \
--embedding-hidden-size 128 \
--no-rnn-aggregation True \
--fast-lr 0.05 \
--inner-loop-grad-clip 20.0 \
--num-updates 5 \
--num-batches-meta-train 60000 \
--num-batches-meta-val 100 \
--meta-batch-size 10 \
--slow-lr 0.001 \
--model-grad-clip 0.0 \
--dataset multimodal_few_shot \
--multimodal_few_shot omniglot miniimagenet cifar bird aircraft \
--num-classes-per-batch 5 \
--num-train-samples-per-class 5 \
--num-val-samples-per-class-meta-train 15 \
--num-val-samples-per-class-meta-val 15 \
--common-img-side-len 84 \
--common-img-channel 3 \
--output-folder mmaml_five_5w5s \
--device cuda \
--device-number 3 \
--log-interval 50 \
--save-interval 1000